openapi: 3.0.3
info:
  title: Family server rest api
  description: |-
    Family server rest api for managing server resources and accessing server application.
    Mostly this API will be used by server UI.
  contact:
    name: Arnab and Sudeshna. 
    url: http://192.168.18.27/
  version: 1.0.0
servers:
  - url: http://localhost:5000/v1
tags:
  - name: rest-info
    description: dev info about rest-api
paths:
  /version:
    get:
      tags:
        - rest-info
      summary: Getting rest related info.
      description: Getting rest related info.
      responses:
        '200':
          description: Rest api information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppInfo'          

components:
  schemas:
    AppInfo:
      type: object
      properties:
        appName:
          type: string
          example: family-server
        appVersion:
          type: string
          example: 1.0.1
