"""Adding asset tracker table

Revision ID: 54aae96e39e9
Revises: 90bf7cb32077
Create Date: 2026-05-08 22:03:58.078585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54aae96e39e9'
down_revision: Union[str, Sequence[str], None] = '90bf7cb32077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_tracker',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('asset_value', sa.Integer(), nullable=False),
    sa.Column('asset_owner', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('asset_name', 'asset_owner', name='uq_asset_tracker_name_owner')
    )
    op.create_index(op.f('ix_asset_tracker_asset_id'), 'asset_tracker', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_tracker_asset_id'), table_name='asset_tracker')
    op.drop_table('asset_tracker')
    # ### end Alembic commands ###
