"""adding unique constraints to event_tracker table

Revision ID: 90bf7cb32077
Revises: bf73c02e06b9
Create Date: 2026-04-18 07:59:31.752702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90bf7cb32077'
down_revision: Union[str, Sequence[str], None] = 'bf73c02e06b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_event_tracker_day_month_name', 'event_tracker', ['day', 'month', 'event_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_event_tracker_day_month_name', 'event_tracker', type_='unique')
    # ### end Alembic commands ###
