"""adding columns: annual investment, return and setpup

Revision ID: bccaa3821686
Revises: 54aae96e39e9
Create Date: 2026-05-29 15:47:36.407184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bccaa3821686'
down_revision: Union[str, Sequence[str], None] = '54aae96e39e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_tracker', sa.Column('annual_investment', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('asset_tracker', sa.Column('annual_return', sa.Numeric(precision=3, scale=1), nullable=False))
    op.add_column('asset_tracker', sa.Column('annual_step_up', sa.Numeric(precision=3, scale=1), nullable=False))
    op.alter_column('asset_tracker', 'asset_value',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_tracker', 'asset_value',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('asset_tracker', 'annual_step_up')
    op.drop_column('asset_tracker', 'annual_return')
    op.drop_column('asset_tracker', 'annual_investment')
    # ### end Alembic commands ###
