"""event tracker - initial schema

Revision ID: bf73c02e06b9
Revises:
Create Date: 2026-04-18 07:50:21.301318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf73c02e06b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'event_tracker',
        sa.Column('event_id', sa.String(length=36), nullable=False),
        sa.Column('day', sa.Integer(), nullable=False),
        sa.Column('month', sa.Integer(), nullable=False),
        sa.Column('event_name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_event_tracker_event_id'), 'event_tracker', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_tracker_event_id'), table_name='event_tracker')
    op.drop_table('event_tracker')
    # ### end Alembic commands ###
