"""create weather tables

Revision ID: e451a8efec6d
Revises: None
Create Date: 2026-01-05 21:07:35.424530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e451a8efec6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_data',
                    sa.Column('dt', sa.DateTime(), nullable=False),
                    sa.Column('pressure', sa.Float(), nullable=False),
                    sa.Column('temperature', sa.Float(), nullable=False),
                    sa.Column('humidity', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('dt')
                    )
    op.create_index(op.f('ix_weather_data_dt'), 'weather_data', ['dt'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_data_dt'), table_name='weather_data')
    op.drop_table('weather_data')
    # ### end Alembic commands ###
